import React, { Suspense } from 'react'

/**
 * Mapping of country's ISO-3 code to the flag component
 */
const flagMap = {
  AFG: React.lazy(() => import('./icons/AFG')),
  AGO: React.lazy(() => import('./icons/AGO')),
  ALB: React.lazy(() => import('./icons/ALB')),
  AND: React.lazy(() => import('./icons/AND')),
  ARE: React.lazy(() => import('./icons/ARE')),
  ARG: React.lazy(() => import('./icons/ARG')),
  ARM: React.lazy(() => import('./icons/ARM')),
  ATG: React.lazy(() => import('./icons/ATG')),
  AUS: React.lazy(() => import('./icons/AUS')),
  AUT: React.lazy(() => import('./icons/AUT')),
  AZE: React.lazy(() => import('./icons/AZE')),
  BDI: React.lazy(() => import('./icons/BDI')),
  BEL: React.lazy(() => import('./icons/BEL')),
  BEN: React.lazy(() => import('./icons/BEN')),
  BFA: React.lazy(() => import('./icons/BFA')),
  BGD: React.lazy(() => import('./icons/BGD')),
  BGR: React.lazy(() => import('./icons/BGR')),
  BHR: React.lazy(() => import('./icons/BHR')),
  BHS: React.lazy(() => import('./icons/BHS')),
  BIH: React.lazy(() => import('./icons/BIH')),
  BLR: React.lazy(() => import('./icons/BLR')),
  BLZ: React.lazy(() => import('./icons/BLZ')),
  BOL: React.lazy(() => import('./icons/BOL')),
  BRA: React.lazy(() => import('./icons/BRA')),
  BRB: React.lazy(() => import('./icons/BRB')),
  BRN: React.lazy(() => import('./icons/BRN')),
  BUR: React.lazy(() => import('./icons/BUR')),
  BWA: React.lazy(() => import('./icons/BWA')),
  CAF: React.lazy(() => import('./icons/CAF')),
  CAN: React.lazy(() => import('./icons/CAN')),
  CHE: React.lazy(() => import('./icons/CHE')),
  CHL: React.lazy(() => import('./icons/CHL')),
  CHN: React.lazy(() => import('./icons/CHN')),
  CIV: React.lazy(() => import('./icons/CIV')),
  CMR: React.lazy(() => import('./icons/CMR')),
  COD: React.lazy(() => import('./icons/COD')),
  COG: React.lazy(() => import('./icons/COG')),
  COL: React.lazy(() => import('./icons/COL')),
  COM: React.lazy(() => import('./icons/COM')),
  CPV: React.lazy(() => import('./icons/CPV')),
  CRI: React.lazy(() => import('./icons/CRI')),
  CUB: React.lazy(() => import('./icons/CUB')),
  CYP: React.lazy(() => import('./icons/CYP')),
  CZE: React.lazy(() => import('./icons/CZE')),
  DEU: React.lazy(() => import('./icons/DEU')),
  DJI: React.lazy(() => import('./icons/DJI')),
  DMA: React.lazy(() => import('./icons/DMA')),
  DNK: React.lazy(() => import('./icons/DNK')),
  DOM: React.lazy(() => import('./icons/DOM')),
  DZA: React.lazy(() => import('./icons/DZA')),
  ECU: React.lazy(() => import('./icons/ECU')),
  EGY: React.lazy(() => import('./icons/EGY')),
  ENG: React.lazy(() => import('./icons/ENG')),
  ERI: React.lazy(() => import('./icons/ERI')),
  ESP: React.lazy(() => import('./icons/ESP')),
  EST: React.lazy(() => import('./icons/EST')),
  ETH: React.lazy(() => import('./icons/ETH')),
  EUE: React.lazy(() => import('./icons/EUE')),
  FIN: React.lazy(() => import('./icons/FIN')),
  FJI: React.lazy(() => import('./icons/FJI')),
  FLK: React.lazy(() => import('./icons/FLK')),
  FRA: React.lazy(() => import('./icons/FRA')),
  FRO: React.lazy(() => import('./icons/FRO')),
  FSM: React.lazy(() => import('./icons/FSM')),
  GAB: React.lazy(() => import('./icons/GAB')),
  GBR: React.lazy(() => import('./icons/GBR')),
  GEO: React.lazy(() => import('./icons/GEO')),
  GGY: React.lazy(() => import('./icons/GGY')),
  GHA: React.lazy(() => import('./icons/GHA')),
  GIB: React.lazy(() => import('./icons/GIB')),
  GIN: React.lazy(() => import('./icons/GIN')),
  GMB: React.lazy(() => import('./icons/GMB')),
  GNB: React.lazy(() => import('./icons/GNB')),
  GNQ: React.lazy(() => import('./icons/GNQ')),
  GRC: React.lazy(() => import('./icons/GRC')),
  GRD: React.lazy(() => import('./icons/GRD')),
  GTM: React.lazy(() => import('./icons/GTM')),
  GUF: React.lazy(() => import('./icons/GUF')),
  GUY: React.lazy(() => import('./icons/GUY')),
  HND: React.lazy(() => import('./icons/HND')),
  HRV: React.lazy(() => import('./icons/HRV')),
  HTI: React.lazy(() => import('./icons/HTI')),
  HUN: React.lazy(() => import('./icons/HUN')),
  IDN: React.lazy(() => import('./icons/IDN')),
  IMN: React.lazy(() => import('./icons/IMN')),
  IND: React.lazy(() => import('./icons/IND')),
  IRL: React.lazy(() => import('./icons/IRL')),
  IRN: React.lazy(() => import('./icons/IRN')),
  IRQ: React.lazy(() => import('./icons/IRQ')),
  ISL: React.lazy(() => import('./icons/ISL')),
  ISR: React.lazy(() => import('./icons/ISR')),
  ITA: React.lazy(() => import('./icons/ITA')),
  JAM: React.lazy(() => import('./icons/JAM')),
  JEY: React.lazy(() => import('./icons/JEY')),
  JOR: React.lazy(() => import('./icons/JOR')),
  JPN: React.lazy(() => import('./icons/JPN')),
  KAZ: React.lazy(() => import('./icons/KAZ')),
  KEN: React.lazy(() => import('./icons/KEN')),
  KGZ: React.lazy(() => import('./icons/KGZ')),
  KHM: React.lazy(() => import('./icons/KHM')),
  KIR: React.lazy(() => import('./icons/KIR')),
  KNA: React.lazy(() => import('./icons/KNA')),
  KOR: React.lazy(() => import('./icons/KOR')),
  KWT: React.lazy(() => import('./icons/KWT')),
  LAO: React.lazy(() => import('./icons/LAO')),
  LBN: React.lazy(() => import('./icons/LBN')),
  LBR: React.lazy(() => import('./icons/LBR')),
  LBY: React.lazy(() => import('./icons/LBY')),
  LCA: React.lazy(() => import('./icons/LCA')),
  LIE: React.lazy(() => import('./icons/LIE')),
  LKA: React.lazy(() => import('./icons/LKA')),
  LSO: React.lazy(() => import('./icons/LSO')),
  LTU: React.lazy(() => import('./icons/LTU')),
  LUX: React.lazy(() => import('./icons/LUX')),
  LVA: React.lazy(() => import('./icons/LVA')),
  MAR: React.lazy(() => import('./icons/MAR')),
  MCO: React.lazy(() => import('./icons/MCO')),
  MDA: React.lazy(() => import('./icons/MDA')),
  MDG: React.lazy(() => import('./icons/MDG')),
  MDV: React.lazy(() => import('./icons/MDV')),
  MEX: React.lazy(() => import('./icons/MEX')),
  MHL: React.lazy(() => import('./icons/MHL')),
  MKD: React.lazy(() => import('./icons/MKD')),
  MLI: React.lazy(() => import('./icons/MLI')),
  MLT: React.lazy(() => import('./icons/MLT')),
  MNE: React.lazy(() => import('./icons/MNE')),
  MNG: React.lazy(() => import('./icons/MNG')),
  MOZ: React.lazy(() => import('./icons/MOZ')),
  MRT: React.lazy(() => import('./icons/MRT')),
  MUS: React.lazy(() => import('./icons/MUS')),
  MWI: React.lazy(() => import('./icons/MWI')),
  MYS: React.lazy(() => import('./icons/MYS')),
  NAM: React.lazy(() => import('./icons/NAM')),
  NER: React.lazy(() => import('./icons/NER')),
  NGA: React.lazy(() => import('./icons/NGA')),
  NIC: React.lazy(() => import('./icons/NIC')),
  NLD: React.lazy(() => import('./icons/NLD')),
  NOR: React.lazy(() => import('./icons/NOR')),
  NPL: React.lazy(() => import('./icons/NPL')),
  NRU: React.lazy(() => import('./icons/NRU')),
  NZL: React.lazy(() => import('./icons/NZL')),
  OMN: React.lazy(() => import('./icons/OMN')),
  PAK: React.lazy(() => import('./icons/PAK')),
  PAN: React.lazy(() => import('./icons/PAN')),
  PER: React.lazy(() => import('./icons/PER')),
  PHL: React.lazy(() => import('./icons/PHL')),
  PLW: React.lazy(() => import('./icons/PLW')),
  PNG: React.lazy(() => import('./icons/PNG')),
  POL: React.lazy(() => import('./icons/POL')),
  PRI: React.lazy(() => import('./icons/PRI')),
  PRK: React.lazy(() => import('./icons/PRK')),
  PRT: React.lazy(() => import('./icons/PRT')),
  PRY: React.lazy(() => import('./icons/PRY')),
  PSE: React.lazy(() => import('./icons/PSE')),
  QAT: React.lazy(() => import('./icons/QAT')),
  ROU: React.lazy(() => import('./icons/ROU')),
  RUS: React.lazy(() => import('./icons/RUS')),
  RWA: React.lazy(() => import('./icons/RWA')),
  SAU: React.lazy(() => import('./icons/SAU')),
  SDN: React.lazy(() => import('./icons/SDN')),
  SEN: React.lazy(() => import('./icons/SEN')),
  SGP: React.lazy(() => import('./icons/SGP')),
  SGS: React.lazy(() => import('./icons/SGS')),
  SLB: React.lazy(() => import('./icons/SLB')),
  SLE: React.lazy(() => import('./icons/SLE')),
  SLV: React.lazy(() => import('./icons/SLV')),
  SMR: React.lazy(() => import('./icons/SMR')),
  SOM: React.lazy(() => import('./icons/SOM')),
  SRB: React.lazy(() => import('./icons/SRB')),
  SSD: React.lazy(() => import('./icons/SSD')),
  STP: React.lazy(() => import('./icons/STP')),
  SUR: React.lazy(() => import('./icons/SUR')),
  SVK: React.lazy(() => import('./icons/SVK')),
  SVN: React.lazy(() => import('./icons/SVN')),
  SWE: React.lazy(() => import('./icons/SWE')),
  SWZ: React.lazy(() => import('./icons/SWZ')),
  SYC: React.lazy(() => import('./icons/SYC')),
  SYR: React.lazy(() => import('./icons/SYR')),
  TCD: React.lazy(() => import('./icons/TCD')),
  TGO: React.lazy(() => import('./icons/TGO')),
  THA: React.lazy(() => import('./icons/THA')),
  TJK: React.lazy(() => import('./icons/TJK')),
  TKM: React.lazy(() => import('./icons/TKM')),
  TMP: React.lazy(() => import('./icons/TMP')),
  TON: React.lazy(() => import('./icons/TON')),
  TTO: React.lazy(() => import('./icons/TTO')),
  TUN: React.lazy(() => import('./icons/TUN')),
  TUR: React.lazy(() => import('./icons/TUR')),
  TUV: React.lazy(() => import('./icons/TUV')),
  TWN: React.lazy(() => import('./icons/TWN')),
  TZA: React.lazy(() => import('./icons/TZA')),
  UGA: React.lazy(() => import('./icons/UGA')),
  UKR: React.lazy(() => import('./icons/UKR')),
  UNK: React.lazy(() => import('./icons/UNK')),
  URY: React.lazy(() => import('./icons/URY')),
  USA: React.lazy(() => import('./icons/USA')),
  UZB: React.lazy(() => import('./icons/UZB')),
  VCT: React.lazy(() => import('./icons/VCT')),
  VEN: React.lazy(() => import('./icons/VEN')),
  VGB: React.lazy(() => import('./icons/VGB')),
  VIR: React.lazy(() => import('./icons/VIR')),
  VNM: React.lazy(() => import('./icons/VNM')),
  VUT: React.lazy(() => import('./icons/VUT')),
  WSM: React.lazy(() => import('./icons/WSM')),
  YEM: React.lazy(() => import('./icons/YEM')),
  ZAF: React.lazy(() => import('./icons/ZAF')),
  ZMB: React.lazy(() => import('./icons/ZMB')),
  ZWE: React.lazy(() => import('./icons/ZWE')),
}

export type CountryCode = keyof typeof flagMap

export function loadFlag(countryCode?: CountryCode): React.ReactElement | null {
  if (!countryCode || !flagMap[countryCode]) {
    return null
  }

  const Flag = flagMap[countryCode]

  if (!Flag) {
    return null
  }

  if (typeof window === 'undefined') {
    return <div style={{ height: 24, width: 24 }} />
  }

  return (
    <Suspense fallback={<div style={{ height: 24, width: 24 }} />}>
      <Flag />
    </Suspense>
  )
}
